default_language_version:
  python: python
default_stages: [commit, push, manual]
repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black-jupyter
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: fix-encoding-pragma
      - id: check-docstring-first
      - id: check-added-large-files
        args: [--maxkb=300000]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.4.0
    hooks:
      - id: flake8-nb
        args:
          [
            "--ignore=E402,E501,W503,C901,E712,F405,F403",
            "--filename=*py,*ipynb",
            "--exclude=code_grave_yard.ipynb",
            "--max-complexity=8",
            "--select=B,C,E,F,W,T,N8",
            "--count",
            "--statistics",
          ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        name: Reorder python imports
        description: This hook reorders imports in python files.
